/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GarcomRouteImport } from './routes/garcom'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as IndexRouteImport } from './routes/index'

const GarcomRoute = GarcomRouteImport.update({
  id: '/garcom',
  path: '/garcom',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/garcom': typeof GarcomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/garcom': typeof GarcomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/garcom': typeof GarcomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caixa' | '/garcom'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caixa' | '/garcom'
  id: '__root__' | '/' | '/caixa' | '/garcom'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixaRoute: typeof CaixaRoute
  GarcomRoute: typeof GarcomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/garcom': {
      id: '/garcom'
      path: '/garcom'
      fullPath: '/garcom'
      preLoaderRoute: typeof GarcomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixaRoute: CaixaRoute,
  GarcomRoute: GarcomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
